---
applications:
- name: sagan-renderer
  buildpack: java_buildpack
  instances: 1
  health-check-type: http
  health-check-http-endpoint: /actuator/health
  memory: 1024M
  disk_quota: 1024M
  routes:
  - route: sagan-renderer.cfapps.io
  services: